### ISSUE TITLE
Support scala3

### ISSUE THREAD

**Issue by mattjacobus** [kitlangton/animus#17]
Great library.  Thanks.  I wanted to try it out on a scala3 app and hacked it to work with the softwaremill 1.x version of magnolia, which is backwards incompatible with the propensity 0.x version.  I likely shouldn't create a pull request because the code isn't clean and it will force you to major version animus.  Let me know if you want the code as an example.  (It's not a huge change and I used some scala3 constructs but didn't change the scala2 implicits and such and I didn't test ADT support.)

**Comment by kitlangton** [comment]
Thanks so much! I’d love to take a look at your code. I’ll definitely update this for 3 :-)

**Comment by mattjacobus** [comment]
Great!  Here are the changes.  Let me know if you prefer a pull request.  https://github.com/mattjacobus/animus

**Comment by kitlangton** [comment]
A pull request would be great, if you have the time. As I am a bit busy at the moment :)

**Comment by tylerjacobus** [comment]
Sorry about the late reply.  It's not clear to me how it's best to support both scala2 and scala3.  Magnolia went through some backward incompatible changes in supporting scala3 which requires changes to Animatable's companion object.  I'm not sure how to pull off conditional compilation in scala so there can be two versions of Animatable, with scala2 using DriveAnimatable.scala and scala3 using object Animatable extends AutoDerivation[Animatable].  We can do it with branching or preprocessing, but perhaps you know a better way.  (I'm not an expert in maintaining libraries in scala and I'm certainly no expert in sbt.)

**Comment by mattjacobus** [comment]
Sorry about the late reply. It's not clear to me how it's best to support both scala2 and scala3. Magnolia went through some backward incompatible changes in supporting scala3 which requires changes to Animatable's companion object. I'm not sure how to pull off conditional compilation in scala so there can be two versions of Animatable, with scala2 using DriveAnimatable.scala and scala3 using object Animatable extends AutoDerivation[Animatable]. We can do it with branching or preprocessing, but perhaps you know a better way. (I'm not an expert in maintaining libraries in scala and I'm certainly no expert in sbt.)

**Comment by kitlangton** [comment]
You did it! :D

**Comment by kyledinh** [comment]
Newbie here, I can't find the Scala 3 version on Maven yet? 
https://mvnrepository.com/artifact/io.github.kitlangton/animus 

What's the procedure/plans for that, or is there resource I can look at use sbt to build it locally?

**Comment by kitlangton** [comment]
@kyledinh I think I forgot to _cut_ a release. I just did that. Let's see if it builds and publishes for Scala 3 :)

**Comment by kyledinh** [comment]
```
https://repo1.maven.org/maven2/io/github/kitlangton/animus_sjs1_3/0.2.2/animus_sjs1_3-0.2.2.jar
  100.0% [##########] 224.6 KiB (602.1 KiB / s)
```

Thanks!!!

**Comment by mattjacobus** [comment]
I guess you can get pretty far with just version specific files.  Thanks
for merging so quickly!
