### ISSUE TITLE
splitTransition elements aren't removed after 1 sec

### ISSUE THREAD

**Issue by mattjacobus** [kitlangton/animus#19]
TransitionSignal fires a handler after 950ms that should remove elements in the TransitionStatus.Removing state.  They aren't removed in that handler because refireMemoized is called before they are removed from the data structures.  The fix seems to work in my tests.  See this change:

https://github.com/mattjacobus/animus/commit/6989b995dc8cc61c186ee71a017ed588ca4ca1c6

**Comment by kitlangton** [comment]
Thank you! I merged the changes :)
I need to rework the transitioning signal at some point :D
